### ISSUE TITLE
After go get go.flipt.io/flipt-client this error occurs

### ISSUE THREAD

**Issue by nhunam** [flipt-io/flipt-client-sdks#558]
```
# go.flipt.io/flipt-client
../../vendor/go.flipt.io/flipt-client/evaluation.go:12:10: fatal error: 'flipt_engine.h' file not found
#include "flipt_engine.h"
```
I'm use MacOS M3. I don't know how to fix it.

**Comment by markphelps** [comment]
@nhunam what version is in your go.mod?

ohh. i see it may be because you are vendoring.. 

I can see `flipt_engine.h` in the latest release when downloading which is what go modules will do. im not sure how vendoring handles it, it may remove non-go files (such as `.h`) files.

![CleanShot 2024-12-05 at 15 28 53](https://github.com/user-attachments/assets/6805f3c5-8813-4d3e-a13e-81752f37b7e8)

let me do some research. cc @GeorgeMac

**Comment by markphelps** [comment]
it looks like by default `go mod vendor` excludes non-go files per https://seankhliao.com/blog/12021-05-09-go-mod-vendor-non-go-things/

we may be able to hack around it though as also described in the blog post

**Comment by markphelps** [comment]
@nhunam can you try to upgrade to the latest version `v0.13.0-rc.3` and see if that resolves your issue?

```
go get -u -v go get go.flipt.io/flipt-client
```

**Comment by nhunam** [comment]
@markphelps : Thank you so much, after upgrade to the latest version, this issue is resolved.
